robot_config:
  general:
    robot_name: crawler
    nonholonomic: true
    flipper_front: true
    flipper_back: true
    gazebo_ros_control: true
    imu: true

  geometry:
    base_length: 0.58
    base_width: 0.26
    base_height: 0.14
    body_length: 0.58
    body_width: 0.13
    body_height: 0.21
    body_gap: 0.31
    flipper_length: 0.37
    flipper_width: 0.033
    flipper_position: 0.29
    flipper_y_offset: 0.30
    wheel_radius: 0.105

  mass:
    base: 8.5
    body_track: 50.0
    body_sprocket: 0.34
    flipper_arm: 1.7
    flipper_track: 3.4
    flipper_sprocket: 0.34

  joints:
    flipper_lower: -2.35619449
    flipper_upper: 2.35619449
    flipper_torque_max: 12000.0
    flipper_effort: 12000.0
    flipper_velocity: 0.9
    flipper_damping: 3.5
    flipper_friction: 0.05
    flipper_position_kp: 300.0
    flipper_position_ki: 0.0
    flipper_position_kd: 95.0
    flipper_position_max_integral_error: 1000.0
    sprocket_effort: 1500.0
    sprocket_velocity: 100.0

  continuous_track:
    enabled: true
    pitch_diameter: 0.31
    elements_per_round: 24
    belt_element_length: 0.026
    belt_thickness: 0.026
    grouser_height: 0.013
    mu: 0.5
    min_depth: 0.0005
    contact_kp: 150000.0
    contact_kd: 3000.0
    contact_max_vel: 0.01
    implicit_spring_damper: 1

  output:
    urdf: ../../urdf/large_crawler.urdf
